###


GET http://localhost:4000/



###


GET http://localhost:4000/post
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWZjNjUzZjc4MmE4NjcwMjRjNTEyOSIsImlhdCI6MTY1MDQ0OTUxNSwiZXhwIjoxNjUwNDUzMTE1fQ.c2Bi_y5AGOOJjy8OeyP3hu0k9rG1AO8dt-TK59R7XuE


###


GET http://localhost:4000/item
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWZjNjUzZjc4MmE4NjcwMjRjNTEyOSIsImlhdCI6MTY1MTIyMzc4MiwiZXhwIjoxNjUzMjk3MzgyfQ.bSB4ou4mAzMoK0qlI7OqRcF0nfbadaCYMqbwOAPucVA
###

###


GET http://localhost:4000/auth

###

GET http://localhost:4000/code


GET http://localhost:4000/post/62557ee28a121576951e3127

###


POST http://localhost:4000/post
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWZjNjUzZjc4MmE4NjcwMjRjNTEyOSIsImlhdCI6MTY1MDQ0OTUxNSwiZXhwIjoxNjUwNDUzMTE1fQ.c2Bi_y5AGOOJjy8OeyP3hu0k9rG1AO8dt-TK59R7XuE
Content-Type: application/json

{
    "message" : "this is my authorized new post",
    "sender" : "neriya"
}

###



POST http://localhost:4000/item
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWZjNjUzZjc4MmE4NjcwMjRjNTEyOSIsImlhdCI6MTY1MDQ0OTUxNSwiZXhwIjoxNjUwNDUzMTE1fQ.c2Bi_y5AGOOJjy8OeyP3hu0k9rG1AO8dt-TK59R7XuE
Content-Type: application/json

{
    "itemname": "Gaming Mouse",
    "itemdescription": "Ergonomic mouse comfortable to use",
    "itemprice": 10,
    "itemrating": 8.6,
    "itemquantity": 20,
    "itempictures": ["pic1.png"]
}

###

POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "firstname" :"matan",
    "lastname" :"sofer" ,
    "email" : "matansofer@gmail.com",
    "password" : "12345", 
    "isadmin":true 
}

###


POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email" : "neriyazudi@gmail.com",
    "password" : "12345"
}

###

POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email" : "matansofer@gmail.com",
    "password" : "12345"
}

###


POST http://localhost:4000/auth/logout
Content-Type: application/json

{
    "message" : "this is my new post",
    "sender" : "Eliav"
}